#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WR_Prüfungen
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BSL_WR")]
	public partial class DatabaseConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertPrüfer(Prüfer instance);
    partial void UpdatePrüfer(Prüfer instance);
    partial void DeletePrüfer(Prüfer instance);
    partial void InsertImport(Import instance);
    partial void UpdateImport(Import instance);
    partial void DeleteImport(Import instance);
    partial void InsertKunde(Kunde instance);
    partial void UpdateKunde(Kunde instance);
    partial void DeleteKunde(Kunde instance);
    partial void InsertPrüfung(Prüfung instance);
    partial void UpdatePrüfung(Prüfung instance);
    partial void DeletePrüfung(Prüfung instance);
    #endregion
		
		public DatabaseConnectionDataContext() : 
				base(global::WR_Prüfungen.Properties.Settings.Default.BSL_WRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Prüfer> Prüfer
		{
			get
			{
				return this.GetTable<Prüfer>();
			}
		}
		
		public System.Data.Linq.Table<Import> Import
		{
			get
			{
				return this.GetTable<Import>();
			}
		}
		
		public System.Data.Linq.Table<Kunde> Kunde
		{
			get
			{
				return this.GetTable<Kunde>();
			}
		}
		
		public System.Data.Linq.Table<Prüfung> Prüfung
		{
			get
			{
				return this.GetTable<Prüfung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prüfer")]
	public partial class Prüfer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private EntitySet<Prüfung> _Prüfung;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Prüfer()
		{
			this._Prüfung = new EntitySet<Prüfung>(new Action<Prüfung>(this.attach_Prüfung), new Action<Prüfung>(this.detach_Prüfung));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prüfer_Prüfung", Storage="_Prüfung", ThisKey="Id", OtherKey="Id_Prüfer")]
		public EntitySet<Prüfung> Prüfung
		{
			get
			{
				return this._Prüfung;
			}
			set
			{
				this._Prüfung.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prüfung(Prüfung entity)
		{
			this.SendPropertyChanging();
			entity.Prüfer = this;
		}
		
		private void detach_Prüfung(Prüfung entity)
		{
			this.SendPropertyChanging();
			entity.Prüfer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Import")]
	public partial class Import : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Import()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kunde")]
	public partial class Kunde : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Nummer;
		
		private string _Firma;
		
		private string _Straße;
		
		private string _Stadt;
		
		private string _Land;
		
		private string _PLZ;
		
		private string _Ansprechnpartner;
		
		private string _Telefon;
		
		private string _Mobil;
		
		private string _EMail;
		
		private string _Web;
		
		private string _Sonstige;
		
		private EntitySet<Prüfung> _Prüfung;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNummerChanging(System.Nullable<int> value);
    partial void OnNummerChanged();
    partial void OnFirmaChanging(string value);
    partial void OnFirmaChanged();
    partial void OnStraßeChanging(string value);
    partial void OnStraßeChanged();
    partial void OnStadtChanging(string value);
    partial void OnStadtChanged();
    partial void OnLandChanging(string value);
    partial void OnLandChanged();
    partial void OnPLZChanging(string value);
    partial void OnPLZChanged();
    partial void OnAnsprechnpartnerChanging(string value);
    partial void OnAnsprechnpartnerChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnMobilChanging(string value);
    partial void OnMobilChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnWebChanging(string value);
    partial void OnWebChanged();
    partial void OnSonstigeChanging(string value);
    partial void OnSonstigeChanged();
    #endregion
		
		public Kunde()
		{
			this._Prüfung = new EntitySet<Prüfung>(new Action<Prüfung>(this.attach_Prüfung), new Action<Prüfung>(this.detach_Prüfung));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nummer", DbType="Int")]
		public System.Nullable<int> Nummer
		{
			get
			{
				return this._Nummer;
			}
			set
			{
				if ((this._Nummer != value))
				{
					this.OnNummerChanging(value);
					this.SendPropertyChanging();
					this._Nummer = value;
					this.SendPropertyChanged("Nummer");
					this.OnNummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firma", DbType="VarChar(50)")]
		public string Firma
		{
			get
			{
				return this._Firma;
			}
			set
			{
				if ((this._Firma != value))
				{
					this.OnFirmaChanging(value);
					this.SendPropertyChanging();
					this._Firma = value;
					this.SendPropertyChanged("Firma");
					this.OnFirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Straße", DbType="VarChar(50)")]
		public string Straße
		{
			get
			{
				return this._Straße;
			}
			set
			{
				if ((this._Straße != value))
				{
					this.OnStraßeChanging(value);
					this.SendPropertyChanging();
					this._Straße = value;
					this.SendPropertyChanged("Straße");
					this.OnStraßeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stadt", DbType="VarChar(30)")]
		public string Stadt
		{
			get
			{
				return this._Stadt;
			}
			set
			{
				if ((this._Stadt != value))
				{
					this.OnStadtChanging(value);
					this.SendPropertyChanging();
					this._Stadt = value;
					this.SendPropertyChanged("Stadt");
					this.OnStadtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land", DbType="VarChar(30)")]
		public string Land
		{
			get
			{
				return this._Land;
			}
			set
			{
				if ((this._Land != value))
				{
					this.OnLandChanging(value);
					this.SendPropertyChanging();
					this._Land = value;
					this.SendPropertyChanged("Land");
					this.OnLandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLZ", DbType="VarChar(10)")]
		public string PLZ
		{
			get
			{
				return this._PLZ;
			}
			set
			{
				if ((this._PLZ != value))
				{
					this.OnPLZChanging(value);
					this.SendPropertyChanging();
					this._PLZ = value;
					this.SendPropertyChanged("PLZ");
					this.OnPLZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ansprechnpartner", DbType="VarChar(100)")]
		public string Ansprechnpartner
		{
			get
			{
				return this._Ansprechnpartner;
			}
			set
			{
				if ((this._Ansprechnpartner != value))
				{
					this.OnAnsprechnpartnerChanging(value);
					this.SendPropertyChanging();
					this._Ansprechnpartner = value;
					this.SendPropertyChanged("Ansprechnpartner");
					this.OnAnsprechnpartnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobil", DbType="VarChar(50)")]
		public string Mobil
		{
			get
			{
				return this._Mobil;
			}
			set
			{
				if ((this._Mobil != value))
				{
					this.OnMobilChanging(value);
					this.SendPropertyChanging();
					this._Mobil = value;
					this.SendPropertyChanged("Mobil");
					this.OnMobilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(30)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="VarChar(50)")]
		public string Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this.OnWebChanging(value);
					this.SendPropertyChanging();
					this._Web = value;
					this.SendPropertyChanged("Web");
					this.OnWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonstige", DbType="VarChar(MAX)")]
		public string Sonstige
		{
			get
			{
				return this._Sonstige;
			}
			set
			{
				if ((this._Sonstige != value))
				{
					this.OnSonstigeChanging(value);
					this.SendPropertyChanging();
					this._Sonstige = value;
					this.SendPropertyChanged("Sonstige");
					this.OnSonstigeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_Prüfung", Storage="_Prüfung", ThisKey="Id", OtherKey="Id_Kunde")]
		public EntitySet<Prüfung> Prüfung
		{
			get
			{
				return this._Prüfung;
			}
			set
			{
				this._Prüfung.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prüfung(Prüfung entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = this;
		}
		
		private void detach_Prüfung(Prüfung entity)
		{
			this.SendPropertyChanging();
			entity.Kunde = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prüfung")]
	public partial class Prüfung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Prüfdatum;
		
		private System.Nullable<System.DateTime> _Produktionsdatum;
		
		private string _Charge;
		
		private string _Bundnummer;
		
		private System.Nullable<double> _Du;
		
		private System.Nullable<double> _Dgs;
		
		private System.Nullable<double> _Re;
		
		private System.Nullable<double> _Rm;
		
		private System.Nullable<double> _RmRe;
		
		private System.Nullable<double> _Agt;
		
		private System.Nullable<double> _fR;
		
		private System.Nullable<double> _se1;
		
		private System.Nullable<double> _se2;
		
		private System.Nullable<double> _se3;
		
		private System.Nullable<double> _se4;
		
		private System.Nullable<double> _a1m;
		
		private System.Nullable<double> _a2m;
		
		private System.Nullable<double> _a3m;
		
		private System.Nullable<double> _a4m;
		
		private System.Nullable<double> _a1_025;
		
		private System.Nullable<double> _a2_025;
		
		private System.Nullable<double> _a3_025;
		
		private System.Nullable<double> _a4_025;
		
		private System.Nullable<double> _a1_075;
		
		private System.Nullable<double> _a2_075;
		
		private System.Nullable<double> _a3_075;
		
		private System.Nullable<double> _a4_075;
		
		private System.Nullable<double> _c1;
		
		private System.Nullable<double> _c2;
		
		private System.Nullable<double> _c3;
		
		private System.Nullable<double> _c4;
		
		private System.Nullable<int> _Id_Prüfer;
		
		private System.Nullable<double> _Alpha;
		
		private System.Nullable<double> _Beta;
		
		private System.Nullable<bool> _Gesendet;
		
		private System.Nullable<int> _Id_Kunde;
		
		private string _Art;
		
		private EntityRef<Kunde> _Kunde;
		
		private EntityRef<Prüfer> _Prüfer;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPrüfdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnPrüfdatumChanged();
    partial void OnProduktionsdatumChanging(System.Nullable<System.DateTime> value);
    partial void OnProduktionsdatumChanged();
    partial void OnChargeChanging(string value);
    partial void OnChargeChanged();
    partial void OnBundnummerChanging(string value);
    partial void OnBundnummerChanged();
    partial void OnDuChanging(System.Nullable<double> value);
    partial void OnDuChanged();
    partial void OnDgsChanging(System.Nullable<double> value);
    partial void OnDgsChanged();
    partial void OnReChanging(System.Nullable<double> value);
    partial void OnReChanged();
    partial void OnRmChanging(System.Nullable<double> value);
    partial void OnRmChanged();
    partial void OnRmReChanging(System.Nullable<double> value);
    partial void OnRmReChanged();
    partial void OnAgtChanging(System.Nullable<double> value);
    partial void OnAgtChanged();
    partial void OnfRChanging(System.Nullable<double> value);
    partial void OnfRChanged();
    partial void Onse1Changing(System.Nullable<double> value);
    partial void Onse1Changed();
    partial void Onse2Changing(System.Nullable<double> value);
    partial void Onse2Changed();
    partial void Onse3Changing(System.Nullable<double> value);
    partial void Onse3Changed();
    partial void Onse4Changing(System.Nullable<double> value);
    partial void Onse4Changed();
    partial void Ona1mChanging(System.Nullable<double> value);
    partial void Ona1mChanged();
    partial void Ona2mChanging(System.Nullable<double> value);
    partial void Ona2mChanged();
    partial void Ona3mChanging(System.Nullable<double> value);
    partial void Ona3mChanged();
    partial void Ona4mChanging(System.Nullable<double> value);
    partial void Ona4mChanged();
    partial void Ona1_025Changing(System.Nullable<double> value);
    partial void Ona1_025Changed();
    partial void Ona2_025Changing(System.Nullable<double> value);
    partial void Ona2_025Changed();
    partial void Ona3_025Changing(System.Nullable<double> value);
    partial void Ona3_025Changed();
    partial void Ona4_025Changing(System.Nullable<double> value);
    partial void Ona4_025Changed();
    partial void Ona1_075Changing(System.Nullable<double> value);
    partial void Ona1_075Changed();
    partial void Ona2_075Changing(System.Nullable<double> value);
    partial void Ona2_075Changed();
    partial void Ona3_075Changing(System.Nullable<double> value);
    partial void Ona3_075Changed();
    partial void Ona4_075Changing(System.Nullable<double> value);
    partial void Ona4_075Changed();
    partial void Onc1Changing(System.Nullable<double> value);
    partial void Onc1Changed();
    partial void Onc2Changing(System.Nullable<double> value);
    partial void Onc2Changed();
    partial void Onc3Changing(System.Nullable<double> value);
    partial void Onc3Changed();
    partial void Onc4Changing(System.Nullable<double> value);
    partial void Onc4Changed();
    partial void OnId_PrüferChanging(System.Nullable<int> value);
    partial void OnId_PrüferChanged();
    partial void OnAlphaChanging(System.Nullable<double> value);
    partial void OnAlphaChanged();
    partial void OnBetaChanging(System.Nullable<double> value);
    partial void OnBetaChanged();
    partial void OnGesendetChanging(System.Nullable<bool> value);
    partial void OnGesendetChanged();
    partial void OnId_KundeChanging(System.Nullable<int> value);
    partial void OnId_KundeChanged();
    partial void OnArtChanging(string value);
    partial void OnArtChanged();
    #endregion
		
		public Prüfung()
		{
			this._Kunde = default(EntityRef<Kunde>);
			this._Prüfer = default(EntityRef<Prüfer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prüfdatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Prüfdatum
		{
			get
			{
				return this._Prüfdatum;
			}
			set
			{
				if ((this._Prüfdatum != value))
				{
					this.OnPrüfdatumChanging(value);
					this.SendPropertyChanging();
					this._Prüfdatum = value;
					this.SendPropertyChanged("Prüfdatum");
					this.OnPrüfdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Produktionsdatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Produktionsdatum
		{
			get
			{
				return this._Produktionsdatum;
			}
			set
			{
				if ((this._Produktionsdatum != value))
				{
					this.OnProduktionsdatumChanging(value);
					this.SendPropertyChanging();
					this._Produktionsdatum = value;
					this.SendPropertyChanged("Produktionsdatum");
					this.OnProduktionsdatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charge", DbType="VarChar(10)")]
		public string Charge
		{
			get
			{
				return this._Charge;
			}
			set
			{
				if ((this._Charge != value))
				{
					this.OnChargeChanging(value);
					this.SendPropertyChanging();
					this._Charge = value;
					this.SendPropertyChanged("Charge");
					this.OnChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bundnummer", DbType="VarChar(10)")]
		public string Bundnummer
		{
			get
			{
				return this._Bundnummer;
			}
			set
			{
				if ((this._Bundnummer != value))
				{
					this.OnBundnummerChanging(value);
					this.SendPropertyChanging();
					this._Bundnummer = value;
					this.SendPropertyChanged("Bundnummer");
					this.OnBundnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Du", DbType="Float")]
		public System.Nullable<double> Du
		{
			get
			{
				return this._Du;
			}
			set
			{
				if ((this._Du != value))
				{
					this.OnDuChanging(value);
					this.SendPropertyChanging();
					this._Du = value;
					this.SendPropertyChanged("Du");
					this.OnDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dgs", DbType="Float")]
		public System.Nullable<double> Dgs
		{
			get
			{
				return this._Dgs;
			}
			set
			{
				if ((this._Dgs != value))
				{
					this.OnDgsChanging(value);
					this.SendPropertyChanging();
					this._Dgs = value;
					this.SendPropertyChanged("Dgs");
					this.OnDgsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Re", DbType="Float")]
		public System.Nullable<double> Re
		{
			get
			{
				return this._Re;
			}
			set
			{
				if ((this._Re != value))
				{
					this.OnReChanging(value);
					this.SendPropertyChanging();
					this._Re = value;
					this.SendPropertyChanged("Re");
					this.OnReChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rm", DbType="Float")]
		public System.Nullable<double> Rm
		{
			get
			{
				return this._Rm;
			}
			set
			{
				if ((this._Rm != value))
				{
					this.OnRmChanging(value);
					this.SendPropertyChanging();
					this._Rm = value;
					this.SendPropertyChanged("Rm");
					this.OnRmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RmRe", DbType="Float")]
		public System.Nullable<double> RmRe
		{
			get
			{
				return this._RmRe;
			}
			set
			{
				if ((this._RmRe != value))
				{
					this.OnRmReChanging(value);
					this.SendPropertyChanging();
					this._RmRe = value;
					this.SendPropertyChanged("RmRe");
					this.OnRmReChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agt", DbType="Float")]
		public System.Nullable<double> Agt
		{
			get
			{
				return this._Agt;
			}
			set
			{
				if ((this._Agt != value))
				{
					this.OnAgtChanging(value);
					this.SendPropertyChanging();
					this._Agt = value;
					this.SendPropertyChanged("Agt");
					this.OnAgtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fR", DbType="Float")]
		public System.Nullable<double> fR
		{
			get
			{
				return this._fR;
			}
			set
			{
				if ((this._fR != value))
				{
					this.OnfRChanging(value);
					this.SendPropertyChanging();
					this._fR = value;
					this.SendPropertyChanged("fR");
					this.OnfRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se1", DbType="Float")]
		public System.Nullable<double> se1
		{
			get
			{
				return this._se1;
			}
			set
			{
				if ((this._se1 != value))
				{
					this.Onse1Changing(value);
					this.SendPropertyChanging();
					this._se1 = value;
					this.SendPropertyChanged("se1");
					this.Onse1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se2", DbType="Float")]
		public System.Nullable<double> se2
		{
			get
			{
				return this._se2;
			}
			set
			{
				if ((this._se2 != value))
				{
					this.Onse2Changing(value);
					this.SendPropertyChanging();
					this._se2 = value;
					this.SendPropertyChanged("se2");
					this.Onse2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se3", DbType="Float")]
		public System.Nullable<double> se3
		{
			get
			{
				return this._se3;
			}
			set
			{
				if ((this._se3 != value))
				{
					this.Onse3Changing(value);
					this.SendPropertyChanging();
					this._se3 = value;
					this.SendPropertyChanged("se3");
					this.Onse3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se4", DbType="Float")]
		public System.Nullable<double> se4
		{
			get
			{
				return this._se4;
			}
			set
			{
				if ((this._se4 != value))
				{
					this.Onse4Changing(value);
					this.SendPropertyChanging();
					this._se4 = value;
					this.SendPropertyChanged("se4");
					this.Onse4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a1m", DbType="Float")]
		public System.Nullable<double> a1m
		{
			get
			{
				return this._a1m;
			}
			set
			{
				if ((this._a1m != value))
				{
					this.Ona1mChanging(value);
					this.SendPropertyChanging();
					this._a1m = value;
					this.SendPropertyChanged("a1m");
					this.Ona1mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a2m", DbType="Float")]
		public System.Nullable<double> a2m
		{
			get
			{
				return this._a2m;
			}
			set
			{
				if ((this._a2m != value))
				{
					this.Ona2mChanging(value);
					this.SendPropertyChanging();
					this._a2m = value;
					this.SendPropertyChanged("a2m");
					this.Ona2mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a3m", DbType="Float")]
		public System.Nullable<double> a3m
		{
			get
			{
				return this._a3m;
			}
			set
			{
				if ((this._a3m != value))
				{
					this.Ona3mChanging(value);
					this.SendPropertyChanging();
					this._a3m = value;
					this.SendPropertyChanged("a3m");
					this.Ona3mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a4m", DbType="Float")]
		public System.Nullable<double> a4m
		{
			get
			{
				return this._a4m;
			}
			set
			{
				if ((this._a4m != value))
				{
					this.Ona4mChanging(value);
					this.SendPropertyChanging();
					this._a4m = value;
					this.SendPropertyChanged("a4m");
					this.Ona4mChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a1_025", DbType="Float")]
		public System.Nullable<double> a1_025
		{
			get
			{
				return this._a1_025;
			}
			set
			{
				if ((this._a1_025 != value))
				{
					this.Ona1_025Changing(value);
					this.SendPropertyChanging();
					this._a1_025 = value;
					this.SendPropertyChanged("a1_025");
					this.Ona1_025Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a2_025", DbType="Float")]
		public System.Nullable<double> a2_025
		{
			get
			{
				return this._a2_025;
			}
			set
			{
				if ((this._a2_025 != value))
				{
					this.Ona2_025Changing(value);
					this.SendPropertyChanging();
					this._a2_025 = value;
					this.SendPropertyChanged("a2_025");
					this.Ona2_025Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a3_025", DbType="Float")]
		public System.Nullable<double> a3_025
		{
			get
			{
				return this._a3_025;
			}
			set
			{
				if ((this._a3_025 != value))
				{
					this.Ona3_025Changing(value);
					this.SendPropertyChanging();
					this._a3_025 = value;
					this.SendPropertyChanged("a3_025");
					this.Ona3_025Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a4_025", DbType="Float")]
		public System.Nullable<double> a4_025
		{
			get
			{
				return this._a4_025;
			}
			set
			{
				if ((this._a4_025 != value))
				{
					this.Ona4_025Changing(value);
					this.SendPropertyChanging();
					this._a4_025 = value;
					this.SendPropertyChanged("a4_025");
					this.Ona4_025Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a1_075", DbType="Float")]
		public System.Nullable<double> a1_075
		{
			get
			{
				return this._a1_075;
			}
			set
			{
				if ((this._a1_075 != value))
				{
					this.Ona1_075Changing(value);
					this.SendPropertyChanging();
					this._a1_075 = value;
					this.SendPropertyChanged("a1_075");
					this.Ona1_075Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a2_075", DbType="Float")]
		public System.Nullable<double> a2_075
		{
			get
			{
				return this._a2_075;
			}
			set
			{
				if ((this._a2_075 != value))
				{
					this.Ona2_075Changing(value);
					this.SendPropertyChanging();
					this._a2_075 = value;
					this.SendPropertyChanged("a2_075");
					this.Ona2_075Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a3_075", DbType="Float")]
		public System.Nullable<double> a3_075
		{
			get
			{
				return this._a3_075;
			}
			set
			{
				if ((this._a3_075 != value))
				{
					this.Ona3_075Changing(value);
					this.SendPropertyChanging();
					this._a3_075 = value;
					this.SendPropertyChanged("a3_075");
					this.Ona3_075Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a4_075", DbType="Float")]
		public System.Nullable<double> a4_075
		{
			get
			{
				return this._a4_075;
			}
			set
			{
				if ((this._a4_075 != value))
				{
					this.Ona4_075Changing(value);
					this.SendPropertyChanging();
					this._a4_075 = value;
					this.SendPropertyChanged("a4_075");
					this.Ona4_075Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c1", DbType="Float")]
		public System.Nullable<double> c1
		{
			get
			{
				return this._c1;
			}
			set
			{
				if ((this._c1 != value))
				{
					this.Onc1Changing(value);
					this.SendPropertyChanging();
					this._c1 = value;
					this.SendPropertyChanged("c1");
					this.Onc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c2", DbType="Float")]
		public System.Nullable<double> c2
		{
			get
			{
				return this._c2;
			}
			set
			{
				if ((this._c2 != value))
				{
					this.Onc2Changing(value);
					this.SendPropertyChanging();
					this._c2 = value;
					this.SendPropertyChanged("c2");
					this.Onc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c3", DbType="Float")]
		public System.Nullable<double> c3
		{
			get
			{
				return this._c3;
			}
			set
			{
				if ((this._c3 != value))
				{
					this.Onc3Changing(value);
					this.SendPropertyChanging();
					this._c3 = value;
					this.SendPropertyChanged("c3");
					this.Onc3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c4", DbType="Float")]
		public System.Nullable<double> c4
		{
			get
			{
				return this._c4;
			}
			set
			{
				if ((this._c4 != value))
				{
					this.Onc4Changing(value);
					this.SendPropertyChanging();
					this._c4 = value;
					this.SendPropertyChanged("c4");
					this.Onc4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Prüfer", DbType="Int")]
		public System.Nullable<int> Id_Prüfer
		{
			get
			{
				return this._Id_Prüfer;
			}
			set
			{
				if ((this._Id_Prüfer != value))
				{
					if (this._Prüfer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PrüferChanging(value);
					this.SendPropertyChanging();
					this._Id_Prüfer = value;
					this.SendPropertyChanged("Id_Prüfer");
					this.OnId_PrüferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alpha", DbType="Float")]
		public System.Nullable<double> Alpha
		{
			get
			{
				return this._Alpha;
			}
			set
			{
				if ((this._Alpha != value))
				{
					this.OnAlphaChanging(value);
					this.SendPropertyChanging();
					this._Alpha = value;
					this.SendPropertyChanged("Alpha");
					this.OnAlphaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beta", DbType="Float")]
		public System.Nullable<double> Beta
		{
			get
			{
				return this._Beta;
			}
			set
			{
				if ((this._Beta != value))
				{
					this.OnBetaChanging(value);
					this.SendPropertyChanging();
					this._Beta = value;
					this.SendPropertyChanged("Beta");
					this.OnBetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gesendet", DbType="Bit")]
		public System.Nullable<bool> Gesendet
		{
			get
			{
				return this._Gesendet;
			}
			set
			{
				if ((this._Gesendet != value))
				{
					this.OnGesendetChanging(value);
					this.SendPropertyChanging();
					this._Gesendet = value;
					this.SendPropertyChanged("Gesendet");
					this.OnGesendetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Kunde", DbType="Int")]
		public System.Nullable<int> Id_Kunde
		{
			get
			{
				return this._Id_Kunde;
			}
			set
			{
				if ((this._Id_Kunde != value))
				{
					if (this._Kunde.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_KundeChanging(value);
					this.SendPropertyChanging();
					this._Id_Kunde = value;
					this.SendPropertyChanged("Id_Kunde");
					this.OnId_KundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art", DbType="VarChar(20)")]
		public string Art
		{
			get
			{
				return this._Art;
			}
			set
			{
				if ((this._Art != value))
				{
					this.OnArtChanging(value);
					this.SendPropertyChanging();
					this._Art = value;
					this.SendPropertyChanged("Art");
					this.OnArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kunde_Prüfung", Storage="_Kunde", ThisKey="Id_Kunde", OtherKey="Id", IsForeignKey=true)]
		public Kunde Kunde
		{
			get
			{
				return this._Kunde.Entity;
			}
			set
			{
				Kunde previousValue = this._Kunde.Entity;
				if (((previousValue != value) 
							|| (this._Kunde.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kunde.Entity = null;
						previousValue.Prüfung.Remove(this);
					}
					this._Kunde.Entity = value;
					if ((value != null))
					{
						value.Prüfung.Add(this);
						this._Id_Kunde = value.Id;
					}
					else
					{
						this._Id_Kunde = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kunde");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prüfer_Prüfung", Storage="_Prüfer", ThisKey="Id_Prüfer", OtherKey="Id", IsForeignKey=true)]
		public Prüfer Prüfer
		{
			get
			{
				return this._Prüfer.Entity;
			}
			set
			{
				Prüfer previousValue = this._Prüfer.Entity;
				if (((previousValue != value) 
							|| (this._Prüfer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prüfer.Entity = null;
						previousValue.Prüfung.Remove(this);
					}
					this._Prüfer.Entity = value;
					if ((value != null))
					{
						value.Prüfung.Add(this);
						this._Id_Prüfer = value.Id;
					}
					else
					{
						this._Id_Prüfer = default(Nullable<int>);
					}
					this.SendPropertyChanged("Prüfer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
